version: '3.8'

services:
  postgres_catalog:
    image: postgres:15
    container_name: postgres_catalog
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog
    ports:
      - "5433:5432"
    volumes:
      - pg_catalog_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

volumes:
  pg_catalog_data:
