server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres_catalog:5432/catalog_db
    username: catalog_user
    password: catalog_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
